// <auto-generated />
// Source: shared/native-rpc-protocol.json
using System;
using System.Collections.Generic;

internal static class NativeRpcProtocol
{
    public const string Host = "com.charterion.control";
    public const int MaxMessageBytes = 1048576;
    public static readonly HashSet<string> AllowedMethods = new(StringComparer.Ordinal)
    {
        "health",
        "control.snapshot",
        "browser.report",
        "browser.status",
        "agent.browser-report",
        "agent.runtime-report",
        "agent.rollover-request",
        "agent.rollover-begin",
        "agent.rollover-bootstrap",
        "agent.rollover-complete",
        "agent.rollover-fail",
        "agent.rollover-status",
        "browser.operation-plan",
        "browser.operation-dispatch",
        "browser.operation-settle",
        "incident.report",
        "project.list",
        "agent.list",
        "resource.list",
        "lease.list",
        "events.list",
        "org-work.project-execution",
        "work.snapshot",
        "work.replace",
        "work.mutate",
        "work.batch-mutate",
        "fleet.reconcile",
        "workspace.provision",
        "workspace.list",
    };
}
